spring:
  main:
    banner-mode: "off"
  jpa:
    show-sql: false
    hibernate:
      dialect: org.hibernate.dialect.HSQLDialect
      ddl-auto: update
  datasource:
    driverClassName: org.hsqldb.jdbc.JDBCDriver
    #    TODO define better path
    url: "jdbc:hsqldb:file:distributed_chat_client"
    username: "sa"
    password: "sa"

rsa:
  keySize: 2048

tomp2p:
  port: 4001
  cache:
    enabled: true
    peerdht:
      capacity: 1000
      duration: 300
    usrename:
      capacity: 1000
      duration: 300
    publickey:
      capacity: 1000
      duration: 300
    onlinestate:
      capacity: 1000
      duration: 60
