spring:
  main:
    banner-mode: "off"
    web-application-type: none
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    hibernate:
      dialect: org.hibernate.dialect.HSQLDialect
      ddl-auto: update
  datasource:
    driverClassName: org.hsqldb.jdbc.JDBCDriver
    #    TODO define better path
    url: "jdbc:hsqldb:file:distributed_chat_client"
    username: "sa"
    password: "sa"

rsa:
  keySize: 4096

tomp2p:
  dht:
    ttl: 60
    replicationInterval: 1000
  port: 4001
  cache:
    enabled: true
    peer:
      capacity: 1000
      duration: 60
